import java.util.ArrayList;
import java.util.Collections;

/**
 * This interface specifies and implements a Dijkstra method next()
 * 
 * @author dardeshna
 */
public interface DijkstraMethods {

	/**
	 * Takes the HashMap generated by the Dijkstra object and converts it to an ArrayList
	 * representing the shortest path between the starting node and the specified node
	 * @param node the node
	 * @param dijkstra the Dijkstra object
	 * @return
	 */
	public static ArrayList<String> next(String node, Dijkstra dijkstra) {
		ArrayList<String> path = new ArrayList<String>();
		path.add(node);
		while(!node.equals(dijkstra.startingNode)){
		   node = dijkstra.path.get(node);
		   path.add(node);
		}
		Collections.reverse(path);
		return path;
	}
	
}
